### ISSUE TITLE
Recommended description

### ISSUE THREAD

**Issue by Aya74** [GSG-FC03/Book-App#38]
- [x] Fixing book style, the spacing and make it responsive **[actual time: 5 min]**
- [x] Get the recommended book images from API [**actual time: 01:12:00 hr ]**
- [x] Creating function that open and close the popup **[actual time: 00:45:00 ]**
- [x] Show the book description when the user click on its image **[actual time: 3:00:00 ]**

**Comment by adnan-afana** [comment]
display the book descriptions when clicking on book image
estimated time: 3 hrs
